### ISSUE TITLE
Weird PIDs in a trace

### ISSUE THREAD

**Issue by jllang** [nimble-code/Spin#53]
There's something fishy going on with one of my traces. Here's an excerpt (the line numbers come from GNU Less):
```
   1198 Starting Terminal with pid 5
   1199  17:    proc  0 (:init::1) Model.pml:42 (state 37)      [(run Terminal(y))]
   1200                 :init:(1):w.index = 0
   1201                 :init:(1):w.payload = 0
   1202  18:    proc  0 (:init::1) Model.pml:40 (state 38)      [y = (y+1)]
   1203                 :init:(1):w.index = 0
   1204                 :init:(1):w.payload = 0
   1205                 :init:(0):y = 2
   1206  19:    proc  0 (:init::1) Model.pml:43 (state 39)      [else]
   1207                 :init:(1):w.index = 0
   1208                 :init:(1):w.payload = 0
   1209  20:    proc  0 (:init::1) Model.pml:43 (state 43)      [break]
   1210                 :init:(1):w.index = 0
   1211                 :init:(1):w.payload = 0
   1212 Starting LoadGenerator with pid 6
   1213  21:    proc  0 (:init::1) Model.pml:44 (state 44)      [(run LoadGenerator())]
   1214                 :init:(1):w.index = 0
   1215                 :init:(1):w.payload = 0
   1216  22:    proc  - (convergence:1) _spin_nvr.tmp:148 (state 35)    [(1)]
   1217  23:    proc  5 (LoadGenerator:1) ./LoadGenerator.pml:104 (state 1)     [z = 0]
   1218                 LoadGenerator(6):w.index = 0
   1219                 LoadGenerator(6):w.payload = 0
   1220                 LoadGenerator(5):z = 0
   1221  24:    proc  - (convergence:1) _spin_nvr.tmp:148 (state 35)    [(1)]
   1222  25:    proc  5 (LoadGenerator:1) ./LoadGenerator.pml:104 (state 2)     [((z<=(10-1)))]
   1223                 LoadGenerator(6):w.index = 0
   1224                 LoadGenerator(6):w.payload = 0
```

On line, 1198, a process known as Terminal is started with PID 5. On line 1212, LoadGenerator is started with PID 6. So far, so good.

However, on line 1217, it looks like LoadGenerator has become the process with PID 5. The two equations on lines 1218 and 1219 show the values of local variables of LoadGenerator using PID 6. Confusingly, on line 1220, we have LoadGenerator(5), which I take means that it's the process LoadGenerator with PID 5. What is going on here?

By the way, what is the meaning of this `:1` after the process name on lines 1199, 1202, 1206, 1209, 1213, 1216,1217, 1221, and 1222? It seems that these two characters are constant and they appear always after a process name on these lines representing transitions.

**Comment by nimble-code** [comment]
the pid numbering is a little confusing, due to the fact that the internal numbering during a run is slightly different from what is admitted to the user in the trails
this little example shows it as well
proctype A()
{
	printf("A is pid %d\n", _pid)
	assert(0)
}

init {
	run A()
	0
}

#if 0
never {
	do
	:: true
	od
}
#endif

where you'll see that process A is internally number 2 when the claim is present, but 1 when it is not.
spin tries its best to hide this from the user (the never claim runs as pid 0 when present), but doesn't always succeed, as the above example, and yours, shows.
So, the apparent discrepancy isn't real.
The extra :1 after the process name gives the process 'priority' which is 1 by default, but can also be assigned a different level (see https://spinroot.com/spin/Man/priority.html )

**Comment by jllang** [comment]
Thank you for the clarification!

**Comment by jllang** [comment]
It was just a bit unexpected that the PID can change during a trace.

**Comment by nimble-code** [comment]
well the pid isn't changing -- the reporting of its value just isn't consistent....
